database:
  host: localhost
  port: 5432
  user: root
  password: root
  dbname: root

server:
  host: 127.0.0.1
  port: 8080

authorization:
  realm: my-realm
  secret: w6q5w01eja97dx5fhwvye7rv5kuxn3zj
  identitykey: email

settings:
  multitenant: true
  audit: true

filestore:
  region: my_region
  bucketname: mybucket_name
  domain: my_domain
  keyid: my_key
  secret: my_secret
